name: eff

dependencies:
- base
- mtl
- exceptions

default-extensions:
- GADTs
- BlockArguments
- KindSignatures
- DataKinds
- RankNTypes
- TypeOperators
- MultiParamTypeClasses
- AllowAmbiguousTypes
- TypeFamilies
- UndecidableInstances
- ConstraintKinds
- FlexibleContexts
- MagicHash
- TypeApplications
- ScopedTypeVariables
- FlexibleInstances
- DefaultSignatures
- QuantifiedConstraints
- LambdaCase
- DerivingStrategies
- DeriveAnyClass
- DeriveFunctor
- StandaloneDeriving

library:
  source-dirs:
  - src

executables:
  eff-test:
    dependencies:
    - eff

    main: Main.hs

    source-dirs:
    - app